"use strict";
import express from "express";
import adminUserRoute from "../controllers/users/admin.js";
import workerUserRoute from "../controllers/users/worker.js";
import instructorUserRoute from "../controllers/users/instructor.js";
import studentUserRoute from "../controllers/users/student.js";
import signinRoute from "../controllers/auth/signin.js";
import signUpRoute from "../controllers/auth/singup.js";
import sessionRoute from "../controllers/auth/session.js";
import logoutRoute from "../controllers/auth/logout.js";
import courseRoute from "../controllers/courses/courses.js";
import courseMaterialRoute from "../controllers/courses/materials.js";
import courseSummariesRoute from "../controllers/courses/summaries.js";
import courseAssignmentRoute from "../controllers/courses/assignments.js";
import courseTests from "../controllers/courses/tests.js";
import notificationRoute from "../controllers/notifications/notifications.js";
const router = express.Router();
router.use("/user/admin", adminUserRoute);
router.use("/user/worker", workerUserRoute);
router.use("/user/instructor", instructorUserRoute);
router.use("/user/student", studentUserRoute);
router.use("/auth_sign", signinRoute);
router.use("/auth_create", signUpRoute);
router.use("/auth_session", sessionRoute);
router.use("/auth_logout", logoutRoute);
router.use("/courses", courseRoute);
router.use("/courses/materials", courseMaterialRoute);
router.use("/courses/summaries", courseSummariesRoute);
router.use("/courses/assignments", courseAssignmentRoute);
router.use("/courses/tests", courseTests);
router.use("/notifications", notificationRoute);
export default router;
